application/flicket_admin/models/__init__.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

application/flicket_admin/forms/__init__.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

application/flicket_admin/forms/form_login.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

import bcrypt
from flask_babel import lazy_gettext
from flask_wtf import FlaskForm
from wtforms import BooleanField
from wtforms import PasswordField
from wtforms import StringField
from wtforms.validators import DataRequired

from application.flicket.models.flicket_user import FlicketUser


def login_user_exist(form, field):
    """
    Ensure the username exists.
    :param form:
    :param field:
    :return True False:
    """
    result = FlicketUser.query.filter_by(username=form.username.data)
    if result.count() == 0:
        field.errors.append('Invalid username.')
        return False
    result = result.first()
    if bcrypt.hashpw(form.password.data.encode('utf-8'), result.password) != result.password:
        field.errors.append('Invalid password.')
        return False

    return True


class LogInForm(FlaskForm):
    """ Log in form. """
    username = StringField(lazy_gettext('username'), validators=[DataRequired(), login_user_exist])
    password = PasswordField(lazy_gettext('password'), validators=[DataRequired()])
    remember_me = BooleanField(lazy_gettext('remember_me'), default=False)

application/flicket_admin/scripts/__init__.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

application/flicket_admin/views/__init__.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

from flask import Blueprint

import os

static_folder = os.path.join(os.getcwd(), 'application/home/static')
templates_folder = os.path.join(os.getcwd(), 'application/flicket_admin/templates')
admin_bp = Blueprint('admin_bp', __name__,
                     template_folder=templates_folder,
                     static_folder=static_folder,
                     static_url_path='/home/static',
                     )

application/flicket_admin/views/view_admin.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

import datetime

from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_babel import gettext
from flask_login import current_user
from flask_login import login_required
from flask_principal import identity_loaded
from flask_principal import Permission
from flask_principal import Principal
from flask_principal import RoleNeed
from flask_principal import UserNeed
from application import db as db2, __version__
from application import app, db
from application.flicket.models.flicket_user import FlicketUser
from application.flicket.models.flicket_user import FlicketGroup
from application.flicket.scripts.hash_password import hash_password
from application.flicket_admin.forms.forms_admin import AddGroupForm
from application.flicket_admin.forms.forms_admin import AddUserForm
from application.flicket_admin.forms.forms_admin import EnterPasswordForm
from application.flicket_admin.forms.forms_admin import EditUserForm
from . import admin_bp
from ..models.flicket_config import FlicketConfig
from ...flicket.scripts.flicket_config import set_flicket_config

principals = Principal(app)
# define flicket_admin role need
admin_only = RoleNeed('flicket_admin')
admin_permission = Permission(admin_only)


def create_user(username, password, email=None, name=None, job_title=None, locale=None, disabled=None):
    password = hash_password(password)
    register = FlicketUser(username=username,
                           email=email,
                           name=name,
                           password=password,
                           job_title=job_title,
                           date_added=datetime.datetime.now(),
                           locale=locale,
                           disabled=disabled)
    db.session.add(register)
    db.session.commit()


# add permissions
@identity_loaded.connect_via(app)
def on_identity_loaded(sender, identity):
    # set the identity user object
    print("hy")
    identity.user = current_user
    # Add the UserNeed to the identity
    if hasattr(current_user, 'id'):
        identity.provides.add(UserNeed(current_user.id))

    # Assuming the User model has a list of groups, update the
    # identity with the groups that the user provides
    if hasattr(current_user, 'flicket_groups'):
        the_user = FlicketUser.query.filter_by(id=current_user.id).first()
        for g in the_user.flicket_groups:
            identity.provides.add(RoleNeed('{}'.format(g.group_name)))


@admin_bp.route(app.config['ADMINHOME'])
@login_required
# @admin_permission.require(http_exception=403)
def index():
    # noinspection PyUnresolvedReferences
    return render_template('admin.html', title='Admin')


# shows all users
@admin_bp.route(app.config['ADMINHOME'] + 'users/', methods=['GET', 'POST'])
@admin_bp.route(app.config['ADMINHOME'] + 'users/<int:page>', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)
def users(page=1):
    users = FlicketUser.query.order_by(FlicketUser.username)
    users = users.paginate(page, app.config['posts_per_page'])

    # noinspection PyUnresolvedReferences
    return render_template('admin_users.html', title='Users', users=users)


# add user
@admin_bp.route(app.config['ADMINHOME'] + 'add_user/', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        create_user(form.username.data,
                    form.password.data,
                    email=form.email.data,
                    name=form.name.data,
                    job_title=form.job_title.data,
                    locale=form.locale.data,
                    disabled=form.disabled.data)
        flash(gettext('You have successfully registered new user "{}".'.format(form.username.data)), category='success')
        return redirect(url_for('admin_bp.users'))
    # noinspection PyUnresolvedReferences
    return render_template('admin_user.html', title='Add User', form=form)


# edit user
@admin_bp.route(app.config['ADMINHOME'] + 'edit_user/', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)
def edit_user():
    _id = request.args.get('id')
    user = FlicketUser.query.filter_by(id=_id).first()
    if user:
        form = EditUserForm()
        if form.validate_on_submit():
            # check the username is unique
            if user.username != form.username.data:
                query = FlicketUser.query.filter_by(username=form.username.data)
                if query.count() > 0:
                    flash(gettext('Username already exists'), category='warning')
                else:
                    # change the username.
                    user.username = form.username.data
            # Don't change the password if nothing was entered.
            if form.password.data != '':
                user.password = hash_password(form.password.data)

            user.email = form.email.data
            user.name = form.name.data
            user.job_title = form.job_title.data
            user.disabled = form.disabled.data

            groups = form.groups.data
            # bit hacky but until i get better at this.
            # at least it keeps the groups table clean. :/
            # delete all groups associated with current user.
            user.flicket_groups = []  # this is beautifully simple though
            # add the user to selected groups
            for g in groups:
                group_id = FlicketGroup.query.filter_by(id=g).first()
                group_id.users.append(user)
            db.session.commit()
            flash(gettext("User {} edited.".format(user.username)), category='success')
            return redirect(url_for('admin_bp.edit_user', id=_id))

        # populate form with form data retrieved from database.
        form.user_id.data = user.id
        form.username.data = user.username
        form.email.data = user.email
        form.name.data = user.name
        form.job_title.data = user.job_title
        form.disabled.data = user.disabled
        # define list of preselect groups.
        groups = []
        for g in user.flicket_groups:
            groups.append(g.id)
        form.groups.data = groups
    else:
        flash(gettext("Could not find user."), category='warning')
        return redirect(url_for('admin_bp.index'))

    # noinspection PyUnresolvedReferences
    return render_template('admin_user.html',
                           title='Edit User',
                           admin_edit=True,
                           form=form, user=user)


# Delete user
@admin_bp.route(app.config['ADMINHOME'] + 'delete_user/', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)
def delete_user():
    form = EnterPasswordForm()
    id = request.args.get('id')
    user_details = FlicketUser.query.filter_by(id=id).first()

    # we won't ever delete the flicket_admin user (id = 1)
    if id == '1':
        flash(gettext('Can\'t delete default flicket_admin user.'), category='warning')
        return redirect(url_for('admin_bp.index'))

    if form.validate_on_submit():
        # delete the user.
        flash(gettext('Deleted user {}s'.format(user_details.username)), category='success')
        db.session.delete(user_details)
        db.session.commit()
        return redirect(url_for('admin_bp.users'))
    # populate form with logged in user details
    form.id.data = g.user.id
    # noinspection PyUnresolvedReferences
    return render_template('admin_delete_user.html', title='Delete user',
                           user_details=user_details, form=form)


# Add new groups
@admin_bp.route(app.config['ADMINHOME'] + 'groups/', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)
def groups():
    form = AddGroupForm()
    groups = FlicketGroup.query.all()
    if form.validate_on_submit():
        add_group = FlicketGroup(
            group_name=form.group_name.data
        )
        db.session.add(add_group)
        db.session.commit()
        flash(gettext('New group "{}" added.'.format(form.group_name.data)), category='success')
        return redirect(url_for('admin_bp.groups'))

    # noinspection PyUnresolvedReferences
    return render_template('admin_groups.html', title='Groups', form=form, groups=groups)


# Edit groups
@admin_bp.route(app.config['ADMINHOME'] + 'edit_group/', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)
def admin_edit_group():
    form = AddGroupForm()
    id = request.args.get('id')
    group = FlicketGroup.query.filter_by(id=id).first()

    # if group can't be found in database.
    if not group:
        flash(gettext('Could not find group {}'.format(group.group_name)), category='warning')
        return redirect(url_for('admin_bp.index'))

    # prevent editing of flicket_admin group name as this is hard coded into flicket_admin view permissions.
    if group.group_name == app.config['ADMIN_GROUP_NAME']:
        flash(gettext('Can\'t edit group {}s.'.format(app.config["ADMIN_GROUP_NAME"])), category='warning')
        return redirect(url_for('admin_bp.index'))

    if form.validate_on_submit():
        group.group_name = form.group_name.data
        db.session.commit()
        flash(gettext('Group name changed to {}.'.format(group.group_name)), category='success')
        return redirect(url_for('admin_bp.groups'))
    form.group_name.data = group.group_name

    # noinspection PyUnresolvedReferences
    return render_template('admin_edit_group.html', title='Edit Group', form=form)


# Delete group
@admin_bp.route(app.config['ADMINHOME'] + 'delete_group/', methods=['GET', 'POST'])
@login_required
#@admin_permission.require(http_exception=403)

application/flicket_admin/views/view_config.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

from flask import (flash,
                   redirect,
                   render_template,
                   url_for)
from flask_babel import gettext
from flask_login import login_required

from application import app, db
from application.flicket_admin.forms.form_config import ConfigForm
from application.flicket_admin.models.flicket_config import FlicketConfig

from . import admin_bp
from .view_admin import admin_permission


# Configuration view
@admin_bp.route(app.config['ADMINHOME'] + 'config/', methods=['GET', 'POST'])
@login_required
# @admin_permission.require(http_exception=403)
def config():
    form = ConfigForm()

    config_details = FlicketConfig.query.first()

    if form.validate_on_submit():

        config_details.mail_server = form.mail_server.data
        config_details.mail_port = form.mail_port.data
        config_details.mail_use_tls = form.mail_use_tls.data
        config_details.mail_use_ssl = form.mail_use_ssl.data
        config_details.mail_debug = form.mail_debug.data
        config_details.mail_username = form.mail_username.data

        config_details.mail_default_sender = form.mail_default_sender.data
        config_details.mail_max_emails = form.mail_max_emails.data
        config_details.mail_suppress_send = form.mail_suppress_send.data
        config_details.mail_ascii_attachments = form.mail_ascii_attachments.data

        config_details.application_title = form.application_title.data,
        config_details.posts_per_page = form.posts_per_page.data,
        config_details.allowed_extensions = form.allowed_extensions.data,
        config_details.ticket_upload_folder = form.ticket_upload_folder.data
        config_details.base_url = form.base_url.data

        config_details.use_auth_domain = form.use_auth_domain.data
        config_details.auth_domain = form.auth_domain.data

        config_details.csv_dump_limit = form.csv_dump_limit.data

        config_details.change_category = form.change_category.data
        config_details.change_category_only_admin_or_super_user = form.change_category_only_admin_or_super_user.data

        # Don't change the password if nothing was entered.
        if form.mail_password.data != '':
            config_details.mail_password = form.mail_password.data

        db.session.commit()
        flash(gettext('Config details updated.'), category='success')
        return redirect(url_for('admin_bp.config'))

    # populate form with details from database.
    form.mail_server.data = config_details.mail_server
    form.mail_port.data = config_details.mail_port
    form.mail_use_tls.data = config_details.mail_use_tls
    form.mail_use_ssl.data = config_details.mail_use_ssl
    form.mail_debug.data = config_details.mail_debug
    form.mail_username.data = config_details.mail_username
    form.mail_password.data = config_details.mail_password
    form.mail_default_sender.data = config_details.mail_default_sender
    form.mail_max_emails.data = config_details.mail_max_emails
    form.mail_suppress_send.data = config_details.mail_suppress_send
    form.mail_ascii_attachments.data = config_details.mail_ascii_attachments

    form.application_title.data = config_details.application_title

    form.posts_per_page.data = config_details.posts_per_page
    form.allowed_extensions.data = config_details.allowed_extensions
    form.ticket_upload_folder.data = config_details.ticket_upload_folder
    form.base_url.data = config_details.base_url

    form.use_auth_domain.data = config_details.use_auth_domain
    form.auth_domain.data = config_details.auth_domain

    form.csv_dump_limit.data = config_details.csv_dump_limit

    form.change_category.data = config_details.change_category
    form.change_category_only_admin_or_super_user.data = config_details.change_category_only_admin_or_super_user

    return render_template('admin_config.html',
                           title='Flicket Configuration',
                           form=form)

application/flicket_admin/views/view_email_test.py
#! usr/bin/python3
# -*- coding: utf8 -*-
#
# Flicket - copyright Paul Bourne: evereux@gmail.com

from flask import flash
from flask import Markup
from flask import url_for
from flask import render_template
from flask_babel import gettext
from flask_login import login_required

from application import app
from application.flicket_admin.forms.form_config import EmailTest
from application.flicket.scripts.email import FlicketMail

from . import admin_bp
from .view_admin import admin_permission


# Configuration view
@admin_bp.route(app.config['ADMINHOME'] + 'test_email/', methods=['GET', 'POST'])
@login_required
# @admin_permission.require(http_exception=403)
def email_test():
    form = EmailTest()

    if form.validate_on_submit():
        # send email notification
        mail = FlicketMail()
        mail.test_email([form.email_address.data])
        flash(Markup(gettext(
            'Flicket has tried to send an email to the address you entered. Please check your inbox. If no email has '
            'arrived please double check the <a href="{}{url_for("admin_bp.config")}">config</a>'
            ' settings.'.format(app.config["base_url"]))),
            category='warning')

    return render_template('admin_email_test.html',
                           title='Send Email Test',
                           form=form)

application/flicket_admin/templates/admin.html
<!-- extend from base layout -->
{% extends "flicket_base.html" %}
{% block content %}
    <!-- {{ self._TemplateReference__context.name }} -->
    <div class="container">

        {% include 'admin_menu.html' %}
    </div>
{% endblock %}

application/flicket_admin/templates/admin_config.html
<!-- extend from base layout -->
{% extends "flicket_base.html" %}
{% block content %}
    <!-- {{ self._TemplateReference__context.name }} -->
    <div class="container">

        {% include 'admin_menu.html' %}

        <div class="row m-2 border rounded p-2 bg-white">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <h2 class="text-center">{{ _('Configuration') }}</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col">

                        <form class="form" action="" method="post" name="register">
                            {{ form.hidden_tag() }}
                            <div class="row p-2">
                                <div class="col-3 text-lg">
                                    {{ _('Field') }}
                                </div>
                                <div class="col text-lg">
                                    {{ _('Value') }}
                                </div>
                            </div>
                            {% set insert_button = False %}
                            {%- for field in form if field.widget.input_type != 'hidden' and field.widget.input_type != 'submit' -%}
                                <div class="row form-group p-2">
                                {{ field.label(class="col-3") }}
                                {% if field.type == 'BooleanField' %}
                                    <div class="col-1">
                                {% else %}
                                    <div class="col-9">
                                {% endif %}

                            {{ field(class="form-control form-control-sm") }}
                            {%- if field.name == 'allowed_extensions' -%}
                                {{ _('This must be a comma delimited list.') }}
                            {% endif %}
                            {%- if field.errors -%}
                                <span class="alert alert-warning">
                                        {%- for error in field.errors -%}
                                            {{ error }}.
                                        {%- endfor -%}
                                     </span>
                            {%- endif -%}

                            {%- if field.name == "mail_ascii_attachments" -%}
                                {% set insert_button = True %}
                            {%- endif -%}
                            </div>
                            </div>
                                {%- if insert_button -%}
                                    <div class="row">
                                        <div class="col offset-3">
                                            <a class="btn btn-info" href="{{ url_for('admin_bp.email_test') }}">Test
                                                Email</a>
                                        </div>
                                    </div>
                                {%- endif -%}
                            {%- endfor -%}
                            <div class="form-group">
                                <div class="text-center">
                                    {{ form.submit }}
                                </div>
                            </div>
                            </div>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

application/flicket_admin/templates/admin_groups.html
<!-- extend from base layout -->
{% extends "flicket_base.html" %}
{% block content %}
    <!-- {{ self._TemplateReference__context.name }} -->
    <div class="container">

        {% include 'admin_menu.html' %}

        <div class="row border rounded m-2 p-2 bg-white">
            <div class="col"><h2>{{ title }}</h2>
                <p>
                    {{ _('Click on group name to edit.') }}
                </p>
            </div>
        </div>

        <div class="row border rounded bg-white m-2 p-2">
            <div class="col">
                <div class="row border-bottom m-2">
                    <div class="col">{{ _('Group Name') }}</div>
                    <div class="col">{{ _('Delete') }}</div>
                </div>
                {%- for group in groups -%}
                    <div class="row m-2">
                        <div class="col">
                            <a href="{{ url_for('admin_bp.admin_edit_group', id=group.id) }}">
                                {{ group.group_name }}
                            </a>
                        </div>
                        <div class="col">
                            <a href="{{ url_for('admin_bp.admin_delete_group', id=group.id) }}">
                                {{ _('delete') }}
                            </a>
                        </div>
                    </div>
                {%- endfor -%}

                <hr/>
                <h2>{{ _('Add Group') }}</h2>
                <form action="" method="post" name="add_group">
                    {{ form.hidden_tag() }}
                    <p>
                        {{ _('Please enter group name.') }}
                    </p>
                    <div class="row mb-2">
                        <div class="col">
                            {{ _('Group Name') }}

                        </div>
                        <div class="col">
                            {{ form.group_name(size=(24)) }}
                            {% if form.group_name.errors %}
                                <span style="color: red;">
                            {% for error in form.group_name.errors %}
                                [{{ error }}]
                            {% endfor %}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-center">
                            <input class="btn btn-primary" type="submit" value="add group"/></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

application/flicket_admin/templates/admin_menu.html
<!-- {{ self._TemplateReference__context.name }} -->
<h1 class="m-2 p-2 border rounded bg-white text-center">{{ _('Administration') }}</h1>
<nav class="navbar navbar-expand navbar-dark bg-dark m-2 rounded">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin_bp.index') }}">
                {{ _('Admin Home') }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin_bp.config') }}">
                {{ _('Flicket Config') }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin_bp.users') }}">
                {{ _('Users') }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin_bp.add_user') }}">
                {{ _('Add User') }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin_bp.groups') }}">
                {{ _('Groups') }}
            </a>
        </li>
    </ul>
</nav>

application/flicket_admin/templates/admin_users.html
<!-- extend from base layout -->
{% extends "flicket_base.html" %}

{% block content %}
    <!-- {{ self._TemplateReference__context.name }} -->
    <div class="container">
        {% include 'admin_menu.html' %}
        <div class=" m-2 p-2 row border rounded bg-white">
            <div class="col">
                <h2>{{ title }}</h2>
                <p>
                    {{ _('Click on username to edit.') }}
                </p>
            </div>
        </div>
        <ul class="m-2 pagination pagination-sm">{% for page in users.iter_pages() %}
            {% if page %}
                {% if page != users.page %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('admin_bp.users', page=page, **request.args) }}">
                            {{ page }}
                        </a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <a class="page-link" href="{{ url_for('admin_bp.users', page=page, **request.args) }}">
                            {{ page }}
                        </a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="">...</a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>

        <div class="row">
            <div class="col">
                {% for u in users.items %}

                    <div class="border rounded bg-white m-2 p-1 pl-3 pr-3">

                        <div class="row">

                            <div class="col">
                                <div class="flicket-tickets-title">
                                    {{ _('Username') }}
                                </div>
                                <div class="flicket-tickets-content">
                                    {{ u.username }}
                                    <a href="{{ url_for('admin_bp.edit_user', id=u.id) }}" title="{{ _('edit') }}">
                                        <i class="fas fa-edit"
                                                {%- if u.is_super_user -%}
                                           style="color: blue"
                                                {%- elif u.is_admin -%}
                                           style="color: red"
                                                {%- endif -%}
                                        ></i>
                                    </a>
                                </div>
                            </div>

                            <div class="col">
                                <div class="flicket-tickets-title">
                                    {{ _('Name') }}
                                </div>
                                <div class="flicket-tickets-content">
                                    {{ u.name }}
                                    <a href="{{ url_for('admin_bp.edit_user', id=u.id) }}" title="{{ _('edit') }}">
                                        <i class="fas fa-edit"
                                                {%- if u.is_super_user -%}
                                           style="color: blue"
                                                {%- elif u.is_admin -%}
                                           style="color: red"
                                                {%- endif -%}
                                        ></i>
                                    </a>
                                </div>
                            </div>

                            <div class="col">
                                <div class="flicket-tickets-title">
                                    {{ _('Email') }}
                                </div>
                                <div class="flicket-tickets-content">
                                    <a href="mailto:{{ u.email }}" title="{{ u.email }}">
                                        <i class="fas fa-envelope"></i>
                                    </a>
                                </div>
                            </div>

                            <div class="col">
                                <div class="flicket-tickets-title">
                                    {{ _('Job Title') }}
                                </div>
                                <div class="flicket-tickets-content">
                                    {{ u.job_title }}
                                </div>
                            </div>

                            <div class="col">
                                <div class="flicket-tickets-title">
                                    {{ _('Delete User') }}
                                </div>
                                <div class="flicket-tickets-content">
                                    <a href="{{ url_for('admin_bp.delete_user', id=u.id) }}" title="{{ _('delete') }}">
                                        <i class="fas fa-trash" style="color: red;"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

application/flicket_admin/templates/flashmessages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <!-- {{ self._TemplateReference__context.name }} -->
        <div class="container">
            <div class="alert alert-{{ messages.0.0 }}" role="alert">
                {% for category, message in messages %}
                    {{ message }} <br>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endwith %}